### ISSUE TITLE
Enviar correo a los usuarios

### ISSUE THREAD

**Issue by fcpauldiaz** [fcpauldiaz/plataforma_virtual#36]
Enviar un correo a todos los usuarios asignados a un curso cada vez que se suba un curso. Tiene que haber una opción que permita ya no mandar los correos .

Idea sugerida, colocar un nuevo campo en la base de datos para saber si el usuario desea recibir correos cuando se suba un archivo a un curso. Verificar este campo para mandar el correo cada vez que se sube un archivo y poner por defecto que sí se manda el correo.

**Comment by fcpauldiaz** [comment]
Estaba pensando que va a ser más fácil si se hace una entidad completa para manejar esto @fitocs452

**Comment by fitocs452** [comment]
Para manejar el envío de correos al subir archivos?

**Comment by fcpauldiaz** [comment]
simón. Para hacer una tabla ManyToMany y que el usuario pueda elegir si quiere dejar de recibir correos solo de algún curso en específico

**Comment by fitocs452** [comment]
Vos decís para tener una relación de uno a uno con la tabla usuario y los que estén en esa tabla que reciban el correo?

**Comment by fcpauldiaz** [comment]
Se me ocurrió una mejor idea. Actualmente Usuario tiene una relación ManyToMany a cursos que sirve para la asignación. La idea a nivel lógico es que la relación tenga un atributo que sirva para saber si se debe mandar un correo. A nivel de técnico (symfony) se tendría que crear otra entidad para poder agregar el atributo a la relación y esa entidad tendría que tener relaciones one to many a curso y a usuario para que sea equivalente al ManyToMany.
